import Foundation

enum BeerStyles {
    static let all: [String] = [
        "IPA",
        "Double IPA",
        "Hazy IPA",
        "Pale Ale",
        "Amber Ale",
        "Brown Ale",
        "Blonde Ale",
        "Belgian Ale",
        "Stout",
        "Imperial Stout",
        "Porter",
        "Lager",
        "Pilsner",
        "Light Lager",
        "Wheat Beer",
        "Hefeweizen",
        "Saison",
        "Sour",
        "Gose",
        "Kolsch",
        "Red Ale",
        "Scotch Ale",
        "Barleywine",
        "Tripel",
        "Dubbel",
        "Witbier",
        "Cream Ale",
        "Bock",
        "Dunkel",
        "Marzen",
        "Rauchbier",
        "Hard Seltzer",
        "Cider",
        "Mead",
    ]
}
